services:
  proxy-colectivos:
    image: oven/bun:latest
    container_name: proxy-colectivos
    restart: always
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    build:
      context: ./server/
      dockerfile: dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/proxy"]
      timeout: 30s
      retries: 5
    command: ["bun", "run", "start"]
    volumes:
      - ./server:/usr/src/app
  frontend-colectivos:
    image: npm:22-alpine
    container_name: frontend-colectivos
    build:
      context: ./cyan-cycle/
      dockerfile: dockerfile
    volumes:
      - ./cyan-cycle/src:/usr/code/src
      - ./cyan-cycle/astro.config.mjs:/usr/code/astro.config.mjs
    ports:
      - 4321:4321
    command: ["npm", "run", "dev"]
    depends_on:
      - proxy-colectivos
